spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:/data/cred_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
